Update UI/event detail to development branch
RMIT-FinTech-Club/FinTech-website pull request #29
Opened 2024-05-04 15:09 UTC by JackyDo2005

Update UI/event detail to development branch

2024-05-04 15:59 UTC, Hankaji requested changes
Please address the feedback and make proper changes then commit or create another PR for me.

2024-05-04 15:59 UTC, Hankaji commented on app/events/(components)/card.tsx
> +			<Image
Add lazy loading option

2024-05-04 15:59 UTC, Hankaji commented on app/events/(components)/style.css
Please put your custom style.css inside the folder "styles" located at root folder. Of course inside their specific folder name or just rename this to this specific target (like events-detail.css for example)

2024-05-04 15:59 UTC, Hankaji commented on app/page.tsx
Why put the <Event /> here? this page.tsx is for home page route. Consider putting it in app/events/page.tsx (for events route)

2024-05-04 15:59 UTC, Hankaji commented on package.json
> +    "@nextui-org/card": "^2.0.28",
No need to install @nextui-org/card. The @nextui-org/react already contain the card elements. That will cause duplication in dependencies.

2024-05-05 04:29 UTC, JackyDo2005 commented on app/events/(components)/card.tsx
> +			<Image
suree, gonna implement it a ho

2024-05-05 04:58 UTC, closed without merging